### ISSUE TITLE
Link dyndns exceed the size of the card

### ISSUE THREAD

**Issue by stefanonepa** [ponsfrilus/EPFLArrival#3]
Maybe the cards should be larger, or the link should be on the click on the link?

**Comment by ponsfrilus** [comment]
@stefanonepa I think the `tiles.json` file should have an optional option to specify link's text in case the link is too long.

**Comment by ponsfrilus** [comment]
@stefanonepa can you please specify your browser ? Everythings look good with Firefox 51.0.1 (64-bit):
![image](https://cloud.githubusercontent.com/assets/176002/23022535/a0ada15a-f451-11e6-9f28-b31526630431.png)

**Comment by stefanonepa** [comment]
Chrome: Version 56.0.2924.87 on windows 10 Edu
![image](https://cloud.githubusercontent.com/assets/4907503/23022842/4e263a6c-f453-11e6-9ffc-c03a830033ec.png)

**Comment by stefanonepa** [comment]
I think it can calculated automatically by counting the nomber of char un the url... and hided or replaced...

Or an elegant way will be to manage all the link in the same way, by using a sub component card-details, and adding more properties on it showing in a modal way... no?

**Comment by ponsfrilus** [comment]
Closed https://github.com/ponsfrilus/EPFLArrival/pull/4
